version: '3.8'

services:
  torrent-api:
    build: .
    container_name: torrent-api-prod
    ports:
      - "80:80"
    volumes:
      - ./cache:/var/www/html/cache
      - ./logs:/var/www/html/logs
    environment:
      PHP_MEMORY_LIMIT: 512M
      PHP_MAX_EXECUTION_TIME: 120
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
